version: 3.6.2
name: True Take Media
address1: 480 South Central
address2: Colorado City, AZ 86021
phone: (435) 212-3705
email: kevin@truetakemedia.com
fax: Ha!
facebook: https://www.facebook.com/truetakeofficial/
instagram: https://www.instagram.com/truetakemedia/
snapchat:
lat:
lng:
mapzoom: 13
permalink: /blog/:title/

categories:
- videos
- case studies
- just for fun
- how we do

objectives:
- lead
- reach
- none

excerpt_separator: <!--more-->
collections:
  main-pages:
    output: true
  customers:
    output: true
  industries:
    output: true
    
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      _hide_content: false
      permalink: /blog/:title/
      navclass: /blog/
  -
    scope:
      path: ""
      type: "industries" 
    values:
      layout: "industry"
      _hide_content: false
      permalink: /:title/
      navclass: /industry/


      
_options:
  image_path:
    width: 90
    height: 120
    resize_style: "contain"
    mime_type: "image/jpeg"
    expandable: true
  content:
    width: 90
    height: 120
    resize_style: "cover"
    mime_type: "image/png"