version: 3.6.2
name: True Take Media
address1: 10 North Central St.
address2: 'Colorado City, AZ 86021'
phone: +1 (435) 236-2369
email: kevin@truetakemedia.com
fax: Ha!
facebook: https://www.facebook.com/truetakeofficial/
instagram: https://www.instagram.com/truetakemedia/
snapchat:
lat:
lng:
mapzoom: 13
permalink: /blog/:title/
excerpt_separator: <!--more-->


categories:
- videos
- case studies
- just for fun
- how we do


objectives:
- lead
- reach
- none


collections:
  main-pages:
    output: true
  
    
defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
      type: "posts" # previously `post` in Jekyll 2.2.
    values:
      layout: "post"
      _hide_content: false
      permalink: /blog/:title/
      navclass: /blog/
  -
    scope:
      path: ""
      type: "industries" 
    values:
      layout: "industry"
      _hide_content: false
      permalink: /:title/
      navclass: /industry/
  -
    scope:
      path: ""
      type: "audience-reports" 
    values:
      layout: "audience-report"
      _hide_content: false
      permalink: /customer-base/:title/
