version: 3.0.3
name: True Take Media
address1: 480 South Central
address2: Colorado City, AZ 86021
phone: (435) 212-3705
email: kevin@truetakemedia.com
fax: Ha!
facebook: https://www.facebook.com/truetakeofficial/
instagram: https://www.instagram.com/truetakemedia/
snapchat:
lat:
lng:
mapzoom: 13
permalink: /blog/:title/
categories:
- videos
- case studies
- just for fun
- how we do
excerpt_separator: <!--more-->
collections:
  main-pages:
    output: true
  customers:
    output: true
  industries:
    output: true