version: 3.0.3
name: True Take Media
address1: 480 South Central
address2: Colorado City, AZ 86021
phone: (435) 212-3705
email: kevin@truetakemedia.com
fax: Ha!
facebook:
instagram:
snapchat:
lat: '37.1003124'
lng: '-113.5552788'
mapzoom: 13
permalink: pretty
excerpt_separator: <!--more-->
collections:
  main-pages:
    output: true
  faqs:
    output: true
  case-studies:
    output: true